### ISSUE TITLE
Change License to CC-BY-4.0

### ISSUE THREAD

**Issue by michaelweinold** [maximikos/Brightway2_Intro#9]
Hey, @maximikos! Many thanks for adding an open-source license. We added one of your notebooks [to the new "Learn Brightway" book](https://learn.brightway.dev/content/notebooks/BW25_for_beginners.html). However, for content (rather than software), CC-BY-4.0 makes more sense than BSD. Could you change the license file to reflect that? We would greatly appreciate it!

**Comment by maximikos** [comment]
I see! Thanks for your suggestion. I updated the license to CC-BY-4.0.
